### ISSUE TITLE
Redirect to wiki page?

### ISSUE THREAD

**Issue by gingerbeardman** [nelsonjchen/github-wiki-see-rs#136]
It would be cool if clicking on the see.page link automatically redirected you to GitHub

**Comment by nelsonjchen** [comment]
Ah sorry this is a `WONTFIX`. Or rather if it was fixed this way, it would risk getting the content unindexed or penalized. 

I don't do this because if a search engine crawler visits such a link and gets automatically redirected, it won't index the content. Search engines crawlers will see the content at the link as a redirect, and then just ignore the content at the link and then not index it. In fact, the search engines crawlers will actually land on the original GitHub Wiki page and sees that it's unindexable, making the whole crawl pointless. 

I also do not selectively try to redirect only search engines crawlers and not users. That would be [cloaking](https://developers.google.com/search/docs/advanced/guidelines/cloaking) and it might violate the guidelines. I'm sure that large search engines "secret shopper" the links to check for this automatically. I don't want to risk any penalizing of the content so I err on not doing this approach either. It's probably debatable if the current approach is cloaking "because it provides our users with different results than they expected" but as we all know, some of the search engines are uncaring inhuman organizations and I prefer to err on the side of pleasing the dumb, human-made computers by having a dumb interstitial for all, robots and humans.

The only wikis/pages with this behavior are the [decommissioned wikis that GitHub allows direct indexing of](https://github.com/nelsonjchen/github-wiki-see-rs/blob/master/src/decommission.rs). I actually want this service to fall off search engines for those Wikis and I have the service configured to automatically redirect. Because search engines crawlers will be automatically redirected to GitHub's content and GitHub does allow that content to be indexed on GitHub.com, the content is not at risk of being unindexed.

**Comment by nelsonjchen** [comment]
In place of this, I do try the following:

* Make the buttons and URL to get to the original GitHub page as obvious and easy to tap or click as possible.
* Also make said buttons and URL use `window.replace()` instead of a plain anchor link to make the service's content page disappear in history if the user goes to GitHub. When they press back or look in their history, the service's content page won't be there contaminating it and will go back to their search engine result page or however they got to the service's content page.

**Comment by nelsonjchen** [comment]
Actually, I think I might even back out of the window.replace thing. Looking in Google's search console, that might be tripping Google's redirect nose.

**Comment by nelsonjchen** [comment]
You can see a fight I'm having like in #137.

**Comment by gingerbeardman** [comment]
no worries, i will implement the redirect myself using a browser extension in my setup.

**Comment by nelsonjchen** [comment]
If you do a write up on it, I would love to link to it. Keep me posted!

**Comment by gingerbeardman** [comment]
I use [PageExtender](https://github.com/fphilipe/PageExtender.app) which allows user-defined JS and CSS per domain.

So I create a file: `github-wiki-see.page.js`
Contents:
```js
if (document.getElementById('header_button')) document.querySelector(".visit_url_button").click();
```

That's it!

**Comment by nelsonjchen** [comment]
Hmm, I think I might make a bit of a contract to provide some elements via ID to click.
